version: '3.8' # or any other supported version like '3.9', '4.0', etc.
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./models:/app/models
    depends_on:
      - app
    restart: always
